# Generated by Django 4.1.4 on 2023-04-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='chart_labels',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chart',
            name='chart_values',
            field=models.TextField(blank=True),
        ),
    ]
