# Generated by Django 4.1.4 on 2023-05-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_chart_database_table_chart_distribution_scale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='database_filters',
            field=models.TextField(blank=True),
        ),
    ]
