# Generated by Django 4.1.4 on 2023-05-16 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_chart_database_filters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('database_table', models.CharField(choices=[('root', 'Ведомостям'), ('students', 'Студентам')], default='root', max_length=100)),
                ('database_select', models.CharField(choices=[('"MeanMark"', 'Средняя оценка'), ('"MeanPositiveMark"', 'Средняя ненулевая оценка'), ('"MarkSum"', 'Сумма оценок'), ('"MarkCount"', 'Количество оценок'), ('"MarkPositiveCount"', 'Количество ненулевых оценок'), ('"10"', 'Количество 10'), ('"9"', 'Количество 9'), ('"8"', 'Количество 8'), ('"7"', 'Количество 7'), ('"6"', 'Количество 6'), ('"5"', 'Количество 5'), ('"4"', 'Количество 4'), ('"3"', 'Количество 3'), ('"2"', 'Количество 2'), ('"1"', 'Количество 1'), ('"0"', 'Количество 0')], default='MeanMark', max_length=100)),
                ('aggregation', models.CharField(choices=[('avg', 'Среднее значение'), ('med', 'Медиану'), ('max', 'Максимальное значение'), ('min', 'Минимальное значение'), ('std', 'Стандартное отклонение'), ('sum', 'Сумму')], default='avg', max_length=100)),
                ('database_filters', models.TextField(blank=True)),
                ('value', models.TextField(blank=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboard')),
            ],
        ),
    ]
