# Generated by Django 4.1.4 on 2023-05-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_constant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
    ]
