# Generated by Django 4.1.4 on 2023-05-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_delete_chartcontainer_chart_height_chart_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='left',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='chart',
            name='top',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='constant',
            name='left',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='constant',
            name='top',
            field=models.FloatField(default=0),
        ),
    ]
